import { Video } from "@/types";

export const defaultVideo: Video = {
  modified: { time: "" },
  created: { time: "" },
  _id: "",
  name: "",
  slug: "",
  origin_name: "",
  poster_url: "",
  thumb_url: "",
  content: "",
  type: "",
  status: "",
  is_copyright: false,
  sub_docquyen: false,
  chieurap: false,
  trailer_url: "",
  time: "",
  episode_current: "",
  episode_total: "",
  quality: "",
  lang: "",
  notify: "",
  showtimes: "",
  year: 0,
  view: 0,
  actor: [],
  director: [],
  category: [],
  country: [],
};
